# Generated by Django 2.0.5 on 2018-06-22 06:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180622_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 6, 27, 9, 776926, tzinfo=utc)),
        ),
    ]
